#!/usr/bin/env php
<?php

declare(strict_types=1);

define('FORJIX_START', microtime(true));

// Find autoloader
$autoloadPaths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
];

$autoloaderFound = false;
foreach ($autoloadPaths as $path) {
    if (file_exists($path)) {
        require $path;
        $autoloaderFound = true;
        break;
    }
}

if (!$autoloaderFound) {
    fwrite(STDERR, "Composer autoloader not found. Run 'composer install' first.\n");
    exit(1);
}

use Forjix\Console\Application;

$app = new Application('Forjix', '1.0.0');
$status = $app->run();

exit($status);
